import { Cloud, Wind, Sun, Thermometer, Droplets, CloudRain, CloudLightning, CloudFog, CloudSnow, Compass } from "lucide-react";

export const meteorologyTopics = [
  {
    title: "1. Advanced Atmospheric Structure",
    description: "Test your knowledge on atmospheric structure",
    icon: Cloud,
    path: "quiz/meteorology/1",
  },
  {
    title: "2. Temperature and Heat Exchange",
    description: "Test your knowledge on temperature processes",
    icon: Thermometer,
    path: "quiz/meteorology/2",
  },
  {
    title: "3. Atmospheric Pressure",
    description: "Test your understanding of pressure systems",
    icon: Compass,
    path: "quiz/meteorology/3",
  },
  {
    title: "4. Atmospheric Moisture",
    description: "Test your knowledge on humidity and precipitation",
    icon: Droplets,
    path: "quiz/meteorology/4",
  },
  {
    title: "5. Atmospheric Stability",
    description: "Test your understanding of air stability",
    icon: Wind,
    path: "quiz/meteorology/5",
  },
  {
    title: "6. Cloud Formation",
    description: "Test your knowledge on cloud types and development",
    icon: CloudRain,
    path: "quiz/meteorology/6",
  },
  {
    title: "7. Air Masses and Fronts",
    description: "Test your knowledge on air masses and frontal systems",
    icon: Wind,
    path: "quiz/meteorology/7",
  },
  {
    title: "8. Precipitation",
    description: "Test your knowledge on various forms of precipitation",
    icon: CloudRain,
    path: "quiz/meteorology/8",
  },
  {
    title: "9. Visibility",
    description: "Test your understanding of factors affecting visibility",
    icon: CloudFog,
    path: "quiz/meteorology/9",
  },
  {
    title: "10. Hazardous Weather",
    description: "Test your knowledge on thunderstorms and severe weather",
    icon: CloudLightning,
    path: "quiz/meteorology/10",
  },
  {
    title: "11. Wind Systems",
    description: "Test your understanding of global and local wind patterns",
    icon: Wind,
    path: "quiz/meteorology/11",
  },
  {
    title: "12. Weather Charts",
    description: "Test your knowledge on reading and interpreting weather maps",
    icon: Compass,
    path: "quiz/meteorology/12",
  },
  {
    title: "13. Weather Reports",
    description: "Test your understanding of METAR and TAF reports",
    icon: CloudRain,
    path: "quiz/meteorology/13",
  },
  {
    title: "14. Flight Planning Weather",
    description: "Test your knowledge on applying weather to flight planning",
    icon: Compass,
    path: "quiz/meteorology/14",
  },
  {
    title: "15. Icing Conditions",
    description: "Test your understanding of aircraft icing and its effects",
    icon: CloudSnow,
    path: "quiz/meteorology/15",
  },
  {
    title: "16. Mountain Weather",
    description: "Test your knowledge on mountain wave and terrain effects",
    icon: Cloud,
    path: "quiz/meteorology/16",
  },
  {
    title: "17. Tropical Weather",
    description: "Test your understanding of tropical weather systems",
    icon: Sun,
    path: "quiz/meteorology/17",
  },
  {
    title: "18. Weather Radar",
    description: "Test your knowledge on weather radar interpretation",
    icon: Compass,
    path: "quiz/meteorology/18",
  },
  {
    title: "19. Jet Streams",
    description: "Test your understanding of high-altitude wind patterns",
    icon: Wind,
    path: "quiz/meteorology/19",
  },
  {
    title: "20. Climate Zones",
    description: "Test your knowledge on global climate patterns",
    icon: Sun,
    path: "quiz/meteorology/20",
  },
  {
    title: "21. Seasonal Weather",
    description: "Test your understanding of seasonal weather variations",
    icon: Sun,
    path: "quiz/meteorology/21",
  },
  {
    title: "22. Weather Services",
    description: "Test your knowledge on aviation weather services",
    icon: Cloud,
    path: "quiz/meteorology/22",
  },
  {
    title: "23. Weather Technology",
    description: "Test your understanding of modern weather forecasting tools",
    icon: Compass,
    path: "quiz/meteorology/23",
  },
  {
    title: "24. Atmospheric Circulation",
    description: "Test your knowledge on global air circulation patterns",
    icon: Wind,
    path: "quiz/meteorology/24",
  },
  {
    title: "25. Weather Hazard Avoidance",
    description: "Test your understanding of strategies for avoiding bad weather",
    icon: CloudLightning,
    path: "quiz/meteorology/25",
  },
  {
    title: "26. Weather Decision Making",
    description: "Test your knowledge on applying weather to pilot decisions",
    icon: Cloud,
    path: "quiz/meteorology/26",
  },
  {
    title: "27. Weather Emergency Procedures",
    description: "Test your understanding of handling weather-related emergencies",
    icon: CloudLightning,
    path: "quiz/meteorology/27",
  },
  {
    title: "28. Advanced Weather Theory",
    description: "Test your knowledge on complex meteorological concepts",
    icon: Cloud,
    path: "quiz/meteorology/28",
  },
  {
    title: "29. Weather Review",
    description: "Test your understanding in a comprehensive review of meteorology topics",
    icon: Cloud,
    path: "quiz/meteorology/29",
  }
];
